In [5]:
#3.4.2 각층의 신호 전달 구현하기
import numpy as np

def sigmoid(x):
    return 1 / (1+np.exp(-x))


#입력층에서 1층으로의 신호 전달
X = np.array([1.0, 0.5]) #입력층 뉴런
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]]) #1층의 가중치
B1 = np.array([0.1, 0.2, 0.3]) #1층의 편향

print(X.shape)
print(W1.shape)
print(B1.shape)
A1 = np.dot(X, W1) + B1 # 1층 뉴런들의 값
Z1 = sigmoid(A1) #활성화 함수로 변환된 신호

print(A1)
print(Z1)

#1층에서 2층으로의 신호 전달
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]]) #2층의 가중치
B2 = np.array([0.1, 0.2]) #2층의 편향

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1, W2) + B2 # 2층 뉴런들의 값
Z2 = sigmoid(A2) #활성화 함수로 변환된 신호

print(A2)
print(Z2)

#2층에서 출력층으로의 신호 전달
def identify_function(x):
    return x

W3 = np.array([[0.1, 0.3], [0.2, 0.4]]) #출력층의 가중치
B3 = np.array([0.1, 0.2]) #출력층의 편향

A3 = np.dot(Z2, W3) + B3 # 출력층 뉴런들의 값
Y = identify_function(A3) #활성화 함수로 변환된 신호
print(Y)

(2,)
(2, 3)
(3,)
[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]
(3,)
(3, 2)
(2,)
[0.51615984 1.21402696]
[0.62624937 0.7710107 ]
[0.31682708 0.69627909]


In [7]:
#3.4.3 구현정리
import numpy as np

def sigmoid(x):
    return 1 / (1+np.exp(-x))

def identify_function(x):
    return x

def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])

    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identify_function(a3)

    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)
    


[0.31682708 0.69627909]


In [10]:
#3.5.1 항등함수와 소프트맥스 함수 구현하기
#소프트맥스 함수 구현

a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a) #지수함수
print(exp_a)

sum_exp_a = sum(exp_a) #지수함수의 합
print(sum_exp_a)

y = exp_a/sum_exp_a
print(y)

#함수로 구현
def softmax(a):
    exp_a =np.exp(a)
    sum_exp_a = sum(exp_a)
    y = exp_a/sum_exp_a

    return y

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [15]:
#3.5.2 소프트맥스 함수 구현시 주의점
#소프트맥스의 지수 함수를 계산할때 어떤 정수를 더해도 결과는 바뀌지 않는다는 점을 이용
#오버 플로를 막을 목적으로 입력 신호중 최댓값 이용

a = np.array([1010, 1000, 990])
print(np.exp(a)/np.sum(np.exp(a))) #제대로 계산X
c = np.max(a) # c = 1010 (최댓값)
print(a-c)

print(np.exp(a-c)/np.sum(np.exp(a-c))) # 최댓값을 빼주면 제대로 계산가능

# 오버플로 대책으로 다시구현
def softmax(a):
    c = np.max(a)
    exp_a =np.exp(a-c) #오버플로 대책
    sum_exp_a = sum(exp_a)
    y = exp_a/sum_exp_a

    return y

[nan nan nan]
[  0 -10 -20]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  
