In [14]:
#넘파이
import numpy as np
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)


[1. 2. 3.]


numpy.ndarray

In [16]:
#넘파이 배열
x = np.array([1.0,2.0,3.0])
y = np.array([2.0,4.0,6.0])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

z= np.array([1.0,2.0,3.0])
z/2.0

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


array([0.5, 1. , 1.5])

In [19]:
#넘파이의 N차원 배열
A = np.array([[1,2],[3,4]])
print(A)
B = np.array([[3,0],[0,6]])
print(A+B)
print(A*B)
A*10

[[1 2]
 [3 4]]
[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]


array([[10, 20],
       [30, 40]])